spring:
  application:
    name: springboot-ai-core

openrouter:
  api:
    base-url: https://openrouter.ai/api/v1
    key: ${OPENROUTER_API_KEY}
    model: mistralai/mistral-small-3.2-24b-instruct:free


